backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  # (Tu gardes ta collection budgets si tu l'utilises)
  - name: "budgets"
    label: "Pages Budget"
    folder: "content/budgets"
    create: true
    slug: "{{slug}}"
    extension: "md"
    preview_path: "{{slug}}/"
    fields:
      - { name: "title", label: "Titre (H1)", widget: "string" }
      - { name: "seo_title", label: "SEO Title", widget: "string" }
      - { name: "seo_desc", label: "Meta Description", widget: "string" }
      - { name: "permalink", label: "Permalink (ex: budget-mariage-100-invites/index.html)", widget: "string" }
      - { name: "tags", label: "Tags", widget: "list", default: ["budget"] }
      - { name: "layout", label: "Layout", widget: "hidden", default: "budget.njk" }
      - { name: "body", label: "Contenu", widget: "markdown" }

  # ✅ Collection unique pour toutes les pages du site (FAQ, À propos, Contact, Mentions, etc.)
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    extension: "md"
    preview_path: "{{slug}}/"
    fields:
      - { name: "title", label: "Titre (H1)", widget: "string" }
      - { name: "seo_title", label: "SEO Title", widget: "string", required: false }
      - { name: "seo_desc", label: "Meta Description", widget: "string", required: false }
      - { name: "permalink", label: "Permalink (ex: faq/index.html)", widget: "string" }
      - label: "Type de page"
        name: "layout"
        widget: "select"
        default: "page.njk"
        options:
          - { label: "Page standard", value: "page.njk" }
          - { label: "Page contact (formulaire)", value: "contact.njk" }
      - { name: "body", label: "Contenu", widget: "markdown" }
